# Generated by Django 4.1 on 2022-10-27 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_rename_projects_project'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Testimonals',
            new_name='Testimonal',
        ),
    ]
