# Generated by Django 4.1 on 2022-10-27 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_rename_testimonals_testimonal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='image',
            field=models.ImageField(upload_to='profile/'),
        ),
    ]
