# Generated by Django 4.1 on 2022-10-27 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0004_alter_about_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_img',
            field=models.ImageField(upload_to='project/'),
        ),
        migrations.AlterField(
            model_name='testimonal',
            name='profile_img',
            field=models.ImageField(upload_to='testimonals/'),
        ),
    ]
