# Generated by Django 4.1.3 on 2022-11-18 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0007_alter_about_description_alter_experience_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonal',
            name='title',
            field=models.CharField(max_length=250),
        ),
    ]
