# Generated by Django 4.1.3 on 2022-11-18 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0009_alter_testimonal_recommendation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='project_url',
        ),
    ]
