# Generated by Django 4.1.3 on 2025-01-16 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0013_document_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_img',
            field=models.ImageField(null=True, upload_to='project/'),
        ),
    ]
